# Pytorch Tutorials

In [1]:
#install pytorch using pip commant
!pip install torch torchvision

In [3]:
import torch

In [4]:
#check is GPU is available
torch.cuda.is_available()
#True if GPU is available, else False 

False

## **Tensor basics**

In [5]:
# creating a simple tensor in torch
tensor = torch.rand(3,3) # creating a 3*3 tensor
print(tensor)

tensor([[0.4857, 0.2403, 0.0495],
        [0.4289, 0.1251, 0.1743],
        [0.8043, 0.6833, 0.3853]])


In [6]:
# creating tensors with 0's and 1's
tensor_zeroes = torch.zeros(3,3) # creating tensor of 3*3 size with zeroes
print(tensor_zeroes)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [8]:
# creating tensors with 0's and 1's
tensor_ones = torch.ones(3,3) # creating tensor of 3*3 size with ones
print(tensor_ones)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [9]:
# specifying the dtype of the tensors is done by
tensorX = torch.ones(3,3, dtype=torch.int) # to specify other dtypes, do torch.float, torch.float16 torch.double and so on
print(tensorX.dtype)

torch.int32


In [10]:
# printing the size of the tensors
print(tensorX.size()) # printing the size of the tensor tensorX

torch.Size([3, 3])


In [13]:
# creating tensor from python lists
tensor_from_list = torch.tensor([1, 2, 3, 4, 5])
print(tensor_from_list)

tensor([1, 2, 3, 4, 5])


## Basic operations on tensors

In [16]:
# lets consider two tensors X and Y of random values and of size 3*3
tensor_X = torch.rand(3,3)
tensor_Y = torch.rand(3,3)

print(tensor_X)
print(tensor_Y)

# Adding both the tensors
#element wise addition of the tensors 
tensor_sum = tensor_X + tensor_Y
# the above operation can also be done by
# tensor_sum = torch.add(tensor_X, tensor_Y)
print(tensor_sum)

# performing in-place addition operation
tensor_Y.add_(tensor_X)
print(tensor_Y)

tensor([[0.4452, 0.3003, 0.9618],
        [0.8185, 0.9370, 0.1899],
        [0.2441, 0.9679, 0.3947]])
tensor([[0.3210, 0.3184, 0.2487],
        [0.5994, 0.8849, 0.7035],
        [0.6868, 0.7173, 0.7911]])
tensor([[0.7662, 0.6187, 1.2104],
        [1.4179, 1.8218, 0.8934],
        [0.9309, 1.6852, 1.1858]])
tensor([[0.7662, 0.6187, 1.2104],
        [1.4179, 1.8218, 0.8934],
        [0.9309, 1.6852, 1.1858]])


In [17]:
# subtraction operation on tensors
tensor_X = torch.rand(3,3)
tensor_Y = torch.rand(3,3)

print(tensor_X)
print(tensor_Y)

# performing subtraction operation
tensor_sub = tensor_X - tensor_Y
# above operation can also be done by
# tensor_sub = torch.sub(tensor_X, tensor_Y)
print(tensor_sub)

tensor([[0.9065, 0.0608, 0.2062],
        [0.7183, 0.4859, 0.5968],
        [0.8398, 0.2159, 0.5594]])
tensor([[3.5471e-04, 6.5176e-01, 3.4131e-01],
        [1.1576e-01, 5.3296e-02, 9.9585e-01],
        [2.7035e-01, 7.8502e-01, 3.5026e-01]])
tensor([[ 0.9061, -0.5909, -0.1351],
        [ 0.6025,  0.4326, -0.3991],
        [ 0.5695, -0.5691,  0.2091]])


In [18]:
# multiplication operation on tensors
tensor_X = torch.rand(3,3)
tensor_Y = torch.rand(3,3)

print(tensor_X)
print(tensor_Y)

# performing multiplications operation
tensor_mul = tensor_X * tensor_Y
# above operation can also be done by
# tensor_mul = torch.mul(tensor_X, tensor_Y)
print(tensor_mul)

tensor([[0.7164, 0.8609, 0.3818],
        [0.4759, 0.2543, 0.8694],
        [0.2220, 0.5611, 0.7241]])
tensor([[0.7345, 0.1831, 0.3399],
        [0.0168, 0.9074, 0.2022],
        [0.1727, 0.6534, 0.7763]])
tensor([[0.5262, 0.1577, 0.1298],
        [0.0080, 0.2307, 0.1758],
        [0.0383, 0.3667, 0.5621]])


In [19]:
# division operation on tensors
tensor_X = torch.rand(3,3)
tensor_Y = torch.rand(3,3)

print(tensor_X)
print(tensor_Y)

# performing division operation
tensor_div = tensor_X * tensor_Y
# above operation can also be done by
# tensor_div = torch.mul(tensor_X, tensor_Y)
print(tensor_div)

tensor([[0.0178, 0.6918, 0.1980],
        [0.9581, 0.3018, 0.2728],
        [0.2582, 0.0522, 0.2980]])
tensor([[0.4860, 0.5033, 0.8077],
        [0.9330, 0.5003, 0.5518],
        [0.7744, 0.0605, 0.6489]])
tensor([[0.0086, 0.3482, 0.1599],
        [0.8939, 0.1510, 0.1505],
        [0.1999, 0.0032, 0.1934]])


In [30]:
# slicing of tensors
tensor_full = torch.rand(5,3)
print(tensor_full)

# slicing 
tensor_slice = tensor_full[: 2] # slice first two columns and all rows
print(tensor_slice)

tensor([[0.2777, 0.8649, 0.6376],
        [0.0675, 0.1614, 0.3583],
        [0.8222, 0.7473, 0.0547],
        [0.7872, 0.6211, 0.5292],
        [0.7934, 0.2050, 0.9650]])
tensor([[0.2777, 0.8649, 0.6376],
        [0.0675, 0.1614, 0.3583]])
tensor([0.7872, 0.6211, 0.5292])


In [32]:
tensor_full = torch.rand(5,3)
print(tensor_full)

tensor_slice2 = tensor_full[3, :] # slice 3rd row, and all columns
print(tensor_slice2)

tensor([[0.4528, 0.9177, 0.2068],
        [0.0824, 0.5227, 0.4154],
        [0.3129, 0.7448, 0.6352],
        [0.8006, 0.8225, 0.7225],
        [0.2473, 0.2297, 0.2784]])
tensor([0.8006, 0.8225, 0.7225])


In [38]:
# Reshaping the tensors
tensor_original = torch.rand(10,3) # original tensor of size 10*3
print(tensor_original)
print('original tensor size is ',tensor_original.size())
tensor_reshaped = tensor_original.view(6,5) # reshaping tensor to 6*5 size
print(tensor_reshaped)
print('reshaped tensor size is ',tensor_reshaped.size())
tensor_reshaped2 = tensor_original.view(3,10) # reshaping tensor to 3,10 size
print(tensor_reshaped2)
print('reshaped2 tensor size is ',tensor_reshaped2.size())

tensor([[0.8880, 0.1755, 0.2257],
        [0.1053, 0.5557, 0.2289],
        [0.0352, 0.4088, 0.7401],
        [0.7558, 0.0391, 0.5301],
        [0.0054, 0.6595, 0.4104],
        [0.1487, 0.6137, 0.0873],
        [0.0730, 0.9446, 0.9469],
        [0.3604, 0.9291, 0.5328],
        [0.1961, 0.8106, 0.0046],
        [0.9997, 0.2156, 0.7489]])
original tensor size is  torch.Size([10, 3])
tensor([[0.8880, 0.1755, 0.2257, 0.1053, 0.5557],
        [0.2289, 0.0352, 0.4088, 0.7401, 0.7558],
        [0.0391, 0.5301, 0.0054, 0.6595, 0.4104],
        [0.1487, 0.6137, 0.0873, 0.0730, 0.9446],
        [0.9469, 0.3604, 0.9291, 0.5328, 0.1961],
        [0.8106, 0.0046, 0.9997, 0.2156, 0.7489]])
reshaped tensor size is  torch.Size([6, 5])
tensor([[0.8880, 0.1755, 0.2257, 0.1053, 0.5557, 0.2289, 0.0352, 0.4088, 0.7401,
         0.7558],
        [0.0391, 0.5301, 0.0054, 0.6595, 0.4104, 0.1487, 0.6137, 0.0873, 0.0730,
         0.9446],
        [0.9469, 0.3604, 0.9291, 0.5328, 0.1961, 0.8106, 0.0046, 0.9997

## **Pytorch to numpy and vice-versa**

In [39]:
import numpy as np
import torch

In [42]:
# converting tensors to numpy arrays
tensorA = torch.ones(5) # creating a tensor of ones, of size 5
print(tensorA)
np_array = tensorA.numpy() # .numpy() converts the tensor to a numpy array
print(np_array)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [43]:
# converting numpy arrays to tensors
np_array1 = np.ones(5) # creating numpy array of ones of size 5
print(np_array1)
np_to_tensor = torch.from_numpy(np_array1) # dtype is float64 by default, if you want to change, dtype can be specified
print(np_to_tensor)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


### How to check is GPU is available on your computer

In [44]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

cpu


In [45]:
# transfering tensors to GPU if available 
tensor_to_gpu = torch.rand(5,5)
tensor_to_gpu.to(device) # if gpu is available then the tensor will be transferred to the available gpu else it will remain on cpu

tensor([[0.3301, 0.2548, 0.7886, 0.4607, 0.5681],
        [0.7819, 0.5022, 0.7414, 0.4503, 0.2034],
        [0.5163, 0.7463, 0.0760, 0.3742, 0.9359],
        [0.0491, 0.9469, 0.7518, 0.5167, 0.3486],
        [0.5796, 0.6349, 0.0841, 0.4642, 0.6814]])